wevtutil cl Analytic
wevtutil cl Application
wevtutil cl CaptureLibLog
wevtutil cl DirectShowFilterGraph
wevtutil cl DirectShowPluginControl
wevtutil cl Els_Hyphenation/Analytic
wevtutil cl EndpointMapper
wevtutil cl FirstUXPerf-Analytic
wevtutil cl ForwardedEvents
wevtutil cl HardwareEvents
wevtutil cl IHM_DebugChannel
wevtutil cl Intel-iaLPSS-GPIO/Analytic
wevtutil cl Intel-iaLPSS-I2C/Analytic
wevtutil cl Intel-iaLPSS2-GPIO2/Debug
wevtutil cl Intel-iaLPSS2-GPIO2/Performance
wevtutil cl Intel-iaLPSS2-I2C/Debug
wevtutil cl Intel-iaLPSS2-I2C/Performance
wevtutil cl Internet Explorer
wevtutil cl Key Management Service
wevtutil cl MF_MediaFoundationDeviceProxy
wevtutil cl MedaFoundationVideoProc
wevtutil cl MedaFoundationVideoProcD3D
wevtutil cl MediaFoundationAsyncWrapper
wevtutil cl MediaFoundationContentProtection
wevtutil cl MediaFoundationDS
wevtutil cl MediaFoundationDeviceProxy
wevtutil cl MediaFoundationMediaEngine
wevtutil cl MediaFoundationPerformance
wevtutil cl MediaFoundationPerformanceCore
wevtutil cl MediaFoundationPipeline
wevtutil cl MediaFoundationPlatform
wevtutil cl MediaFoundationSrcPrefetch
wevtutil cl Microsoft-AppV-Client-Streamingux/Debug
wevtutil cl Microsoft-AppV-Client/Admin
wevtutil cl Microsoft-AppV-Client/Debug
wevtutil cl Microsoft-AppV-Client/Operational
wevtutil cl Microsoft-AppV-Client/Virtual Applications
wevtutil cl Microsoft-AppV-SharedPerformance/Analytic
wevtutil cl Microsoft-Client-Licensing-Platform/Admin
wevtutil cl Microsoft-Client-Licensing-Platform/Debug
wevtutil cl Microsoft-Client-Licensing-Platform/Diagnostic
wevtutil cl Microsoft-IE/Diagnostic
wevtutil cl Microsoft-IEFRAME/Diagnostic
wevtutil cl Microsoft-JSDumpHeap/Diagnostic
wevtutil cl Microsoft-OneCore-Setup/Analytic
wevtutil cl Microsoft-PerfTrack-IEFRAME/Diagnostic
wevtutil cl Microsoft-PerfTrack-MSHTML/Diagnostic
wevtutil cl Microsoft-User Experience Virtualization-Admin/Debug
wevtutil cl Microsoft-User Experience Virtualization-Agent Driver/Debug
wevtutil cl Microsoft-User Experience Virtualization-Agent Driver/Operational
wevtutil cl Microsoft-User Experience Virtualization-App Agent/Analytic
wevtutil cl Microsoft-User Experience Virtualization-App Agent/Debug
wevtutil cl Microsoft-User Experience Virtualization-App Agent/Operational
wevtutil cl Microsoft-User Experience Virtualization-IPC/Operational
wevtutil cl Microsoft-User Experience Virtualization-SQM Uploader/Analytic
wevtutil cl Microsoft-User Experience Virtualization-SQM Uploader/Debug
wevtutil cl Microsoft-User Experience Virtualization-SQM Uploader/Operational
wevtutil cl Microsoft-Windows-AAD/Analytic
wevtutil cl Microsoft-Windows-AAD/Operational
wevtutil cl Microsoft-Windows-ADSI/Debug
wevtutil cl Microsoft-Windows-ASN1/Operational
wevtutil cl Microsoft-Windows-ATAPort/General
wevtutil cl Microsoft-Windows-ATAPort/SATA-LPM
wevtutil cl Microsoft-Windows-ActionQueue/Analytic
wevtutil cl Microsoft-Windows-All-User-Install-Agent/Admin
wevtutil cl Microsoft-Windows-AllJoyn/Debug
wevtutil cl Microsoft-Windows-AllJoyn/Operational
wevtutil cl Microsoft-Windows-AppHost/Admin
wevtutil cl Microsoft-Windows-AppHost/ApplicationTracing
wevtutil cl Microsoft-Windows-AppHost/Diagnostic
wevtutil cl Microsoft-Windows-AppHost/Internal
wevtutil cl Microsoft-Windows-AppID/Operational
wevtutil cl Microsoft-Windows-AppLocker/EXE and DLL
wevtutil cl Microsoft-Windows-AppLocker/MSI and Script
wevtutil cl Microsoft-Windows-AppLocker/Packaged app-Deployment
wevtutil cl Microsoft-Windows-AppLocker/Packaged app-Execution
wevtutil cl Microsoft-Windows-AppModel-Runtime/Admin
wevtutil cl Microsoft-Windows-AppModel-Runtime/Analytic
wevtutil cl Microsoft-Windows-AppModel-Runtime/Debug
wevtutil cl Microsoft-Windows-AppModel-Runtime/Diagnostics
wevtutil cl Microsoft-Windows-AppModel-State/Debug
wevtutil cl Microsoft-Windows-AppModel-State/Diagnostic
wevtutil cl Microsoft-Windows-AppReadiness/Admin
wevtutil cl Microsoft-Windows-AppReadiness/Debug
wevtutil cl Microsoft-Windows-AppReadiness/Operational
wevtutil cl Microsoft-Windows-AppSruProv
wevtutil cl Microsoft-Windows-AppXDeployment/Diagnostic
wevtutil cl Microsoft-Windows-AppXDeployment/Operational
wevtutil cl Microsoft-Windows-AppXDeploymentServer/Debug
wevtutil cl Microsoft-Windows-AppXDeploymentServer/Diagnostic
wevtutil cl Microsoft-Windows-AppXDeploymentServer/Operational
wevtutil cl Microsoft-Windows-AppXDeploymentServer/Restricted
wevtutil cl Microsoft-Windows-ApplicabilityEngine/Analytic
wevtutil cl Microsoft-Windows-ApplicabilityEngine/Operational
wevtutil cl Microsoft-Windows-Application Server-Applications/Admin
wevtutil cl Microsoft-Windows-Application Server-Applications/Analytic
wevtutil cl Microsoft-Windows-Application Server-Applications/Debug
wevtutil cl Microsoft-Windows-Application Server-Applications/Operational
wevtutil cl Microsoft-Windows-Application-Experience/Compatibility-Infrastructure-Debug
wevtutil cl Microsoft-Windows-Application-Experience/Program-Compatibility-Assistant
wevtutil cl Microsoft-Windows-Application-Experience/Program-Compatibility-Assistant/Analytic
wevtutil cl Microsoft-Windows-Application-Experience/Program-Compatibility-Assistant/Trace
wevtutil cl Microsoft-Windows-Application-Experience/Program-Compatibility-Troubleshooter
wevtutil cl Microsoft-Windows-Application-Experience/Program-Inventory
wevtutil cl Microsoft-Windows-Application-Experience/Program-Telemetry
wevtutil cl Microsoft-Windows-Application-Experience/Steps-Recorder
wevtutil cl Microsoft-Windows-ApplicationResourceManagementSystem/Diagnostic
wevtutil cl Microsoft-Windows-ApplicationResourceManagementSystem/Operational
wevtutil cl Microsoft-Windows-AppxPackaging/Debug
wevtutil cl Microsoft-Windows-AppxPackaging/Operational
wevtutil cl Microsoft-Windows-AppxPackaging/Performance
wevtutil cl Microsoft-Windows-AssignedAccess/Admin
wevtutil cl Microsoft-Windows-AssignedAccess/Operational
wevtutil cl Microsoft-Windows-AssignedAccessBroker/Admin
wevtutil cl Microsoft-Windows-AssignedAccessBroker/Operational
wevtutil cl Microsoft-Windows-AsynchronousCausality/Causality
wevtutil cl Microsoft-Windows-Audio/CaptureMonitor
wevtutil cl Microsoft-Windows-Audio/GlitchDetection
wevtutil cl Microsoft-Windows-Audio/Informational
wevtutil cl Microsoft-Windows-Audio/Operational
wevtutil cl Microsoft-Windows-Audio/Performance
wevtutil cl Microsoft-Windows-Audio/PlaybackManager
wevtutil cl Microsoft-Windows-Audit/Analytic
wevtutil cl Microsoft-Windows-Authentication User Interface/Operational
wevtutil cl Microsoft-Windows-Authentication/AuthenticationPolicyFailures-DomainController
wevtutil cl Microsoft-Windows-Authentication/ProtectedUser-Client
wevtutil cl Microsoft-Windows-Authentication/ProtectedUserFailures-DomainController
wevtutil cl Microsoft-Windows-Authentication/ProtectedUserSuccesses-DomainController
wevtutil cl Microsoft-Windows-AxInstallService/Log
wevtutil cl Microsoft-Windows-BTH-BTHPORT/HCI
wevtutil cl Microsoft-Windows-BTH-BTHPORT/L2CAP
wevtutil cl Microsoft-Windows-BTH-BTHUSB/Diagnostic
wevtutil cl Microsoft-Windows-BTH-BTHUSB/Performance
wevtutil cl Microsoft-Windows-BackgroundTaskInfrastructure/Diagnostic
wevtutil cl Microsoft-Windows-BackgroundTaskInfrastructure/Operational
wevtutil cl Microsoft-Windows-BackgroundTransfer-ContentPrefetcher/Operational
wevtutil cl Microsoft-Windows-Backup
wevtutil cl Microsoft-Windows-Base-Filtering-Engine-Connections/Operational
wevtutil cl Microsoft-Windows-Base-Filtering-Engine-Resource-Flows/Operational
wevtutil cl Microsoft-Windows-Battery/Diagnostic
wevtutil cl Microsoft-Windows-Biometrics/Analytic
wevtutil cl Microsoft-Windows-Biometrics/Operational
wevtutil cl Microsoft-Windows-BitLocker-DrivePreparationTool/Admin
wevtutil cl Microsoft-Windows-BitLocker-DrivePreparationTool/Operational
wevtutil cl Microsoft-Windows-BitLocker-Driver-Performance/Operational
wevtutil cl Microsoft-Windows-BitLocker/BitLocker Management
wevtutil cl Microsoft-Windows-BitLocker/BitLocker Operational
wevtutil cl Microsoft-Windows-BitLocker/Tracing
wevtutil cl Microsoft-Windows-Bits-Client/Analytic
wevtutil cl Microsoft-Windows-Bits-Client/Operational
wevtutil cl Microsoft-Windows-Bluetooth-BthLEEnum/Operational
wevtutil cl Microsoft-Windows-Bluetooth-BthLEPrepairing/Operational
wevtutil cl Microsoft-Windows-Bluetooth-MTPEnum/Operational
wevtutil cl Microsoft-Windows-Bluetooth-Policy/Operational
wevtutil cl Microsoft-Windows-BranchCache/Operational
wevtutil cl Microsoft-Windows-BranchCacheClientEventProvider/Diagnostic
wevtutil cl Microsoft-Windows-BranchCacheEventProvider/Diagnostic
wevtutil cl Microsoft-Windows-BranchCacheMonitoring/Analytic
wevtutil cl Microsoft-Windows-BranchCacheSMB/Analytic
wevtutil cl Microsoft-Windows-BranchCacheSMB/Operational
wevtutil cl Microsoft-Windows-CAPI2/Catalog Database Debug
wevtutil cl Microsoft-Windows-CAPI2/Operational
wevtutil cl Microsoft-Windows-CDROM/Operational
wevtutil cl Microsoft-Windows-COM/Analytic
wevtutil cl Microsoft-Windows-COM/ApartmentInitialize
wevtutil cl Microsoft-Windows-COM/ApartmentUninitialize
wevtutil cl Microsoft-Windows-COM/Call
wevtutil cl Microsoft-Windows-COM/CreateInstance
wevtutil cl Microsoft-Windows-COM/ExtensionCatalog
wevtutil cl Microsoft-Windows-COM/FreeUnusedLibrary
wevtutil cl Microsoft-Windows-COMRuntime/Activations
wevtutil cl Microsoft-Windows-COMRuntime/MessageProcessing
wevtutil cl Microsoft-Windows-COMRuntime/Tracing
wevtutil cl Microsoft-Windows-CertPoleEng/Operational
wevtutil cl Microsoft-Windows-CertificateServicesClient-CredentialRoaming/Operational
wevtutil cl Microsoft-Windows-CertificateServicesClient-Lifecycle-System/Operational
wevtutil cl Microsoft-Windows-CertificateServicesClient-Lifecycle-User/Operational
wevtutil cl Microsoft-Windows-ClearTypeTextTuner/Diagnostic
wevtutil cl Microsoft-Windows-CloudStorageWizard/Analytic
wevtutil cl Microsoft-Windows-CloudStorageWizard/Operational
wevtutil cl Microsoft-Windows-CloudStore/Debug
wevtutil cl Microsoft-Windows-CloudStore/Operational
wevtutil cl Microsoft-Windows-CmiSetup/Analytic
wevtutil cl Microsoft-Windows-CodeIntegrity/Operational
wevtutil cl Microsoft-Windows-CodeIntegrity/Verbose
wevtutil cl Microsoft-Windows-ComDlg32/Analytic
wevtutil cl Microsoft-Windows-ComDlg32/Debug
wevtutil cl Microsoft-Windows-Compat-Appraiser/Analytic
wevtutil cl Microsoft-Windows-Compat-Appraiser/Operational
wevtutil cl Microsoft-Windows-Containers-Wcifs/Debug
wevtutil cl Microsoft-Windows-Containers-Wcifs/Operational
wevtutil cl Microsoft-Windows-Containers-Wcnfs/Debug
wevtutil cl Microsoft-Windows-Containers-Wcnfs/Operational
wevtutil cl Microsoft-Windows-CoreApplication/Diagnostic
wevtutil cl Microsoft-Windows-CoreApplication/Operational
wevtutil cl Microsoft-Windows-CoreApplication/Tracing
wevtutil cl Microsoft-Windows-CoreSystem-SmsRouter-Events/Debug
wevtutil cl Microsoft-Windows-CoreSystem-SmsRouter-Events/Operational
wevtutil cl Microsoft-Windows-CoreWindow/Analytic
wevtutil cl Microsoft-Windows-CoreWindow/Debug
wevtutil cl Microsoft-Windows-CorruptedFileRecovery-Client/Operational
wevtutil cl Microsoft-Windows-CorruptedFileRecovery-Server/Operational
wevtutil cl Microsoft-Windows-Crashdump/Operational
wevtutil cl Microsoft-Windows-CredUI/Diagnostic
wevtutil cl Microsoft-Windows-Crypto-BCRYPT/Analytic
wevtutil cl Microsoft-Windows-Crypto-CNG/Analytic
wevtutil cl Microsoft-Windows-Crypto-DPAPI/BackUpKeySvc
wevtutil cl Microsoft-Windows-Crypto-DPAPI/Debug
wevtutil cl Microsoft-Windows-Crypto-DPAPI/Operational
wevtutil cl Microsoft-Windows-Crypto-DSSEnh/Analytic
wevtutil cl Microsoft-Windows-Crypto-NCrypt/Operational
wevtutil cl Microsoft-Windows-Crypto-RNG/Analytic
wevtutil cl Microsoft-Windows-Crypto-RSAEnh/Analytic
wevtutil cl Microsoft-Windows-D3D10Level9/Analytic
wevtutil cl Microsoft-Windows-D3D10Level9/PerfTiming
wevtutil cl Microsoft-Windows-DAL-Provider/Analytic
wevtutil cl Microsoft-Windows-DAL-Provider/Operational
wevtutil cl Microsoft-Windows-DAMM/Diagnostic
wevtutil cl Microsoft-Windows-DCLocator/Debug
wevtutil cl Microsoft-Windows-DDisplay/Analytic
wevtutil cl Microsoft-Windows-DDisplay/Logging
wevtutil cl Microsoft-Windows-DLNA-Namespace/Analytic
wevtutil cl Microsoft-Windows-DNS-Client/Operational
wevtutil cl Microsoft-Windows-DSC/Admin
wevtutil cl Microsoft-Windows-DSC/Analytic
wevtutil cl Microsoft-Windows-DSC/Debug
wevtutil cl Microsoft-Windows-DSC/Operational
wevtutil cl Microsoft-Windows-DUI/Diagnostic
wevtutil cl Microsoft-Windows-DUSER/Diagnostic
wevtutil cl Microsoft-Windows-DXGI/Analytic
wevtutil cl Microsoft-Windows-DXGI/Logging
wevtutil cl Microsoft-Windows-DXP/Analytic
wevtutil cl Microsoft-Windows-Data-Pdf/Debug
wevtutil cl Microsoft-Windows-DataIntegrityScan/Admin
wevtutil cl Microsoft-Windows-DataIntegrityScan/CrashRecovery
wevtutil cl Microsoft-Windows-DateTimeControlPanel/Analytic
wevtutil cl Microsoft-Windows-DateTimeControlPanel/Debug
wevtutil cl Microsoft-Windows-DateTimeControlPanel/Operational
wevtutil cl Microsoft-Windows-Deduplication/Diagnostic
wevtutil cl Microsoft-Windows-Deduplication/Operational
wevtutil cl Microsoft-Windows-Deduplication/Performance
wevtutil cl Microsoft-Windows-Deduplication/Scrubbing
wevtutil cl Microsoft-Windows-Defrag-Core/Debug
wevtutil cl Microsoft-Windows-Deplorch/Analytic
wevtutil cl Microsoft-Windows-DesktopActivityModerator/Diagnostic
wevtutil cl Microsoft-Windows-DesktopWindowManager-Diag/Diagnostic
wevtutil cl Microsoft-Windows-DeviceAssociationService/Performance
wevtutil cl Microsoft-Windows-DeviceConfidence/Analytic
wevtutil cl Microsoft-Windows-DeviceGuard/Operational
wevtutil cl Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider/Admin
wevtutil cl Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider/Debug
wevtutil cl Microsoft-Windows-DeviceSetupManager/Admin
wevtutil cl Microsoft-Windows-DeviceSetupManager/Analytic
wevtutil cl Microsoft-Windows-DeviceSetupManager/Debug
wevtutil cl Microsoft-Windows-DeviceSetupManager/Operational
wevtutil cl Microsoft-Windows-DeviceSync/Analytic
wevtutil cl Microsoft-Windows-DeviceSync/Operational
wevtutil cl Microsoft-Windows-DeviceUx/Informational
wevtutil cl Microsoft-Windows-DeviceUx/Performance
wevtutil cl Microsoft-Windows-Devices-Background/Operational
wevtutil cl Microsoft-Windows-Dhcp-Client/Admin
wevtutil cl Microsoft-Windows-Dhcp-Client/Operational
wevtutil cl Microsoft-Windows-Dhcpv6-Client/Admin
wevtutil cl Microsoft-Windows-Dhcpv6-Client/Operational
wevtutil cl Microsoft-Windows-DiagCpl/Debug
wevtutil cl Microsoft-Windows-Diagnosis-AdvancedTaskManager/Analytic
wevtutil cl Microsoft-Windows-Diagnosis-DPS/Analytic
wevtutil cl Microsoft-Windows-Diagnosis-DPS/Debug
wevtutil cl Microsoft-Windows-Diagnosis-DPS/Operational
wevtutil cl Microsoft-Windows-Diagnosis-MSDE/Debug
wevtutil cl Microsoft-Windows-Diagnosis-PCW/Analytic
wevtutil cl Microsoft-Windows-Diagnosis-PCW/Debug
wevtutil cl Microsoft-Windows-Diagnosis-PCW/Operational
wevtutil cl Microsoft-Windows-Diagnosis-PLA/Debug
wevtutil cl Microsoft-Windows-Diagnosis-PLA/Operational
wevtutil cl Microsoft-Windows-Diagnosis-Perfhost/Analytic
wevtutil cl Microsoft-Windows-Diagnosis-Scheduled/Operational
wevtutil cl Microsoft-Windows-Diagnosis-Scripted/Admin
wevtutil cl Microsoft-Windows-Diagnosis-Scripted/Analytic
wevtutil cl Microsoft-Windows-Diagnosis-Scripted/Debug
wevtutil cl Microsoft-Windows-Diagnosis-Scripted/Operational
wevtutil cl Microsoft-Windows-Diagnosis-ScriptedDiagnosticsProvider/Debug
wevtutil cl Microsoft-Windows-Diagnosis-ScriptedDiagnosticsProvider/Operational
wevtutil cl Microsoft-Windows-Diagnosis-WDC/Analytic
wevtutil cl Microsoft-Windows-Diagnosis-WDI/Debug
wevtutil cl Microsoft-Windows-Diagnostics-Networking/Debug
wevtutil cl Microsoft-Windows-Diagnostics-Networking/Operational
wevtutil cl Microsoft-Windows-Diagnostics-PerfTrack-Counters/Diagnostic
wevtutil cl Microsoft-Windows-Diagnostics-PerfTrack/Diagnostic
wevtutil cl Microsoft-Windows-Diagnostics-Performance/Diagnostic
wevtutil cl Microsoft-Windows-Diagnostics-Performance/Diagnostic/Loopback
wevtutil cl Microsoft-Windows-Diagnostics-Performance/Operational
wevtutil cl Microsoft-Windows-Direct3D10/Analytic
wevtutil cl Microsoft-Windows-Direct3D10_1/Analytic
wevtutil cl Microsoft-Windows-Direct3D11/Analytic
wevtutil cl Microsoft-Windows-Direct3D11/Logging
wevtutil cl Microsoft-Windows-Direct3D11/PerfTiming
wevtutil cl Microsoft-Windows-Direct3D12/Analytic
wevtutil cl Microsoft-Windows-Direct3D12/Logging
wevtutil cl Microsoft-Windows-Direct3D12/PerfTiming
wevtutil cl Microsoft-Windows-Direct3D9/Analytic
wevtutil cl Microsoft-Windows-Direct3DShaderCache/Default
wevtutil cl Microsoft-Windows-DirectComposition/Diagnostic
wevtutil cl Microsoft-Windows-DirectManipulation/Diagnostic
wevtutil cl Microsoft-Windows-DirectShow-KernelSupport/Performance
wevtutil cl Microsoft-Windows-DirectSound/Debug
wevtutil cl Microsoft-Windows-DirectWrite-FontCache/Tracing
wevtutil cl Microsoft-Windows-DirectWrite/Tracing
wevtutil cl Microsoft-Windows-Disk/Operational
wevtutil cl Microsoft-Windows-DiskDiagnostic/Operational
wevtutil cl Microsoft-Windows-DiskDiagnosticDataCollector/Operational
wevtutil cl Microsoft-Windows-DiskDiagnosticResolver/Operational
wevtutil cl Microsoft-Windows-Dism-Api/Analytic
wevtutil cl Microsoft-Windows-Dism-Api/ExternalAnalytic
wevtutil cl Microsoft-Windows-Dism-Api/InternalAnalytic
wevtutil cl Microsoft-Windows-Dism-Cli/Analytic
wevtutil cl Microsoft-Windows-DisplayColorCalibration/Debug
wevtutil cl Microsoft-Windows-DisplayColorCalibration/Operational
wevtutil cl Microsoft-Windows-DisplaySwitch/Diagnostic
wevtutil cl Microsoft-Windows-Documents/Performance
wevtutil cl Microsoft-Windows-Dot3MM/Diagnostic
wevtutil cl Microsoft-Windows-DriverFrameworks-UserMode/Operational
wevtutil cl Microsoft-Windows-Dwm-API/Diagnostic
wevtutil cl Microsoft-Windows-Dwm-Core/Diagnostic
wevtutil cl Microsoft-Windows-Dwm-Dwm/Diagnostic
wevtutil cl Microsoft-Windows-Dwm-Redir/Diagnostic
wevtutil cl Microsoft-Windows-Dwm-Udwm/Diagnostic
wevtutil cl Microsoft-Windows-DxgKrnl/Contention
wevtutil cl Microsoft-Windows-DxgKrnl/Diagnostic
wevtutil cl Microsoft-Windows-DxgKrnl/Performance
wevtutil cl Microsoft-Windows-DxgKrnl/Power
wevtutil cl Microsoft-Windows-DxpTaskSyncProvider/Analytic
wevtutil cl Microsoft-Windows-EDP-Application-Learning/Admin
wevtutil cl Microsoft-Windows-EDP-Audit-Regular/Admin
wevtutil cl Microsoft-Windows-EDP-Audit-TCB/Admin
wevtutil cl Microsoft-Windows-EFS/Debug
wevtutil cl Microsoft-Windows-ESE/IODiagnose
wevtutil cl Microsoft-Windows-ESE/Operational
wevtutil cl Microsoft-Windows-EapHost/Analytic
wevtutil cl Microsoft-Windows-EapHost/Debug
wevtutil cl Microsoft-Windows-EapHost/Operational
wevtutil cl Microsoft-Windows-EapMethods-RasChap/Operational
wevtutil cl Microsoft-Windows-EapMethods-RasTls/Operational
wevtutil cl Microsoft-Windows-EapMethods-Sim/Operational
wevtutil cl Microsoft-Windows-EapMethods-Ttls/Operational
wevtutil cl Microsoft-Windows-EaseOfAccess/Diagnostic
wevtutil cl Microsoft-Windows-EmbeddedAppLauncher/Admin
wevtutil cl Microsoft-Windows-EmbeddedAppLauncher/Operational
wevtutil cl Microsoft-Windows-Energy-Estimation-Engine/EventLog
wevtutil cl Microsoft-Windows-Energy-Estimation-Engine/Trace
wevtutil cl Microsoft-Windows-EnhancedStorage-EhStorTcgDrv/Analytic
wevtutil cl Microsoft-Windows-EventCollector/Debug
wevtutil cl Microsoft-Windows-EventCollector/Operational
wevtutil cl Microsoft-Windows-EventLog-WMIProvider/Debug
wevtutil cl Microsoft-Windows-EventLog/Analytic
wevtutil cl Microsoft-Windows-EventLog/Debug
wevtutil cl Microsoft-Windows-FMS/Analytic
wevtutil cl Microsoft-Windows-FMS/Debug
wevtutil cl Microsoft-Windows-FMS/Operational
wevtutil cl Microsoft-Windows-FailoverClustering-Client/Diagnostic
wevtutil cl Microsoft-Windows-Fault-Tolerant-Heap/Operational
wevtutil cl Microsoft-Windows-FileHistory-Catalog/Analytic
wevtutil cl Microsoft-Windows-FileHistory-Catalog/Debug
wevtutil cl Microsoft-Windows-FileHistory-ConfigManager/Analytic
wevtutil cl Microsoft-Windows-FileHistory-ConfigManager/Debug
wevtutil cl Microsoft-Windows-FileHistory-Core/Analytic
wevtutil cl Microsoft-Windows-FileHistory-Core/Debug
wevtutil cl Microsoft-Windows-FileHistory-Core/WHC
wevtutil cl Microsoft-Windows-FileHistory-Engine/Analytic
wevtutil cl Microsoft-Windows-FileHistory-Engine/BackupLog
wevtutil cl Microsoft-Windows-FileHistory-Engine/Debug
wevtutil cl Microsoft-Windows-FileHistory-EventListener/Analytic
wevtutil cl Microsoft-Windows-FileHistory-EventListener/Debug
wevtutil cl Microsoft-Windows-FileHistory-Service/Analytic
wevtutil cl Microsoft-Windows-FileHistory-Service/Debug
wevtutil cl Microsoft-Windows-FileHistory-UI-Events/Analytic
wevtutil cl Microsoft-Windows-FileHistory-UI-Events/Debug
wevtutil cl Microsoft-Windows-FileInfoMinifilter/Operational
wevtutil cl Microsoft-Windows-Firewall-CPL/Diagnostic
wevtutil cl Microsoft-Windows-Folder Redirection/Operational
wevtutil cl Microsoft-Windows-FontGroups/Diagnostic
wevtutil cl Microsoft-Windows-Forwarding/Debug
wevtutil cl Microsoft-Windows-Forwarding/Operational
wevtutil cl Microsoft-Windows-GPIO-ClassExtension/Analytic
wevtutil cl Microsoft-Windows-GenericRoaming/Admin
wevtutil cl Microsoft-Windows-GroupPolicy/Operational
wevtutil cl Microsoft-Windows-HAL/Debug
wevtutil cl Microsoft-Windows-HealthCenter/Debug
wevtutil cl Microsoft-Windows-HealthCenter/Performance
wevtutil cl Microsoft-Windows-HealthCenterCPL/Performance
wevtutil cl Microsoft-Windows-HelloForBusiness/Operational
wevtutil cl Microsoft-Windows-Help/Operational
wevtutil cl Microsoft-Windows-HomeGroup Control Panel Performance/Diagnostic
wevtutil cl Microsoft-Windows-HomeGroup Control Panel/Operational
wevtutil cl Microsoft-Windows-HomeGroup Listener Service/Operational
wevtutil cl Microsoft-Windows-HomeGroup Provider Service Performance/Diagnostic
wevtutil cl Microsoft-Windows-HomeGroup Provider Service/Operational
wevtutil cl Microsoft-Windows-HomeGroup-ListenerService
wevtutil cl Microsoft-Windows-HotspotAuth/Analytic
wevtutil cl Microsoft-Windows-HotspotAuth/Operational
wevtutil cl Microsoft-Windows-HttpService/Log
wevtutil cl Microsoft-Windows-HttpService/Trace
wevtutil cl Microsoft-Windows-Hyper-V-Guest-Drivers/Admin
wevtutil cl Microsoft-Windows-Hyper-V-Guest-Drivers/Analytic
wevtutil cl Microsoft-Windows-Hyper-V-Guest-Drivers/Debug
wevtutil cl Microsoft-Windows-Hyper-V-Guest-Drivers/Diagnose
wevtutil cl Microsoft-Windows-Hyper-V-Guest-Drivers/Operational
wevtutil cl Microsoft-Windows-Hyper-V-NETVSC/Diagnostic
wevtutil cl Microsoft-Windows-IKE/Operational
wevtutil cl Microsoft-Windows-IKEDBG/Debug
wevtutil cl Microsoft-Windows-IME-Broker/Analytic
wevtutil cl Microsoft-Windows-IME-CandidateUI/Analytic
wevtutil cl Microsoft-Windows-IME-CustomerFeedbackManager/Debug
wevtutil cl Microsoft-Windows-IME-CustomerFeedbackManagerUI/Analytic
wevtutil cl Microsoft-Windows-IME-JPAPI/Analytic
wevtutil cl Microsoft-Windows-IME-JPLMP/Analytic
wevtutil cl Microsoft-Windows-IME-JPPRED/Analytic
wevtutil cl Microsoft-Windows-IME-JPSetting/Analytic
wevtutil cl Microsoft-Windows-IME-JPTIP/Analytic
wevtutil cl Microsoft-Windows-IME-KRAPI/Analytic
wevtutil cl Microsoft-Windows-IME-KRTIP/Analytic
wevtutil cl Microsoft-Windows-IME-OEDCompiler/Analytic
wevtutil cl Microsoft-Windows-IME-TCCORE/Analytic
wevtutil cl Microsoft-Windows-IME-TCTIP/Analytic
wevtutil cl Microsoft-Windows-IME-TIP/Analytic
wevtutil cl Microsoft-Windows-IPNAT/Diagnostic
wevtutil cl Microsoft-Windows-IPSEC-SRV/Diagnostic
wevtutil cl Microsoft-Windows-IdCtrls/Analytic
wevtutil cl Microsoft-Windows-IdCtrls/Operational
wevtutil cl Microsoft-Windows-IndirectDisplays-ClassExtension-Events/Diagnostic
wevtutil cl Microsoft-Windows-Input-HIDCLASS-Analytic
wevtutil cl Microsoft-Windows-InputSwitch/Diagnostic
wevtutil cl Microsoft-Windows-International-RegionalOptionsControlPanel/Operational
wevtutil cl Microsoft-Windows-International/Operational
wevtutil cl Microsoft-Windows-Iphlpsvc/Debug
wevtutil cl Microsoft-Windows-Iphlpsvc/Operational
wevtutil cl Microsoft-Windows-Iphlpsvc/Trace
wevtutil cl Microsoft-Windows-KdsSvc/Operational
wevtutil cl Microsoft-Windows-Kerberos/Operational
wevtutil cl Microsoft-Windows-Kernel-Acpi/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-AppCompat/General
wevtutil cl Microsoft-Windows-Kernel-AppCompat/Performance
wevtutil cl Microsoft-Windows-Kernel-ApphelpCache/Analytic
wevtutil cl Microsoft-Windows-Kernel-ApphelpCache/Debug
wevtutil cl Microsoft-Windows-Kernel-ApphelpCache/Operational
wevtutil cl Microsoft-Windows-Kernel-Boot/Analytic
wevtutil cl Microsoft-Windows-Kernel-Boot/Operational
wevtutil cl Microsoft-Windows-Kernel-BootDiagnostics/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-Disk/Analytic
wevtutil cl Microsoft-Windows-Kernel-EventTracing/Admin
wevtutil cl Microsoft-Windows-Kernel-EventTracing/Analytic
wevtutil cl Microsoft-Windows-Kernel-File/Analytic
wevtutil cl Microsoft-Windows-Kernel-IO/Operational
wevtutil cl Microsoft-Windows-Kernel-Interrupt-Steering/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-IoTrace/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-LiveDump/Analytic
wevtutil cl Microsoft-Windows-Kernel-Memory/Analytic
wevtutil cl Microsoft-Windows-Kernel-Network/Analytic
wevtutil cl Microsoft-Windows-Kernel-Pdc/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-Pep/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-PnP/Boot Diagnostic
wevtutil cl Microsoft-Windows-Kernel-PnP/Configuration
wevtutil cl Microsoft-Windows-Kernel-PnP/Configuration Diagnostic
wevtutil cl Microsoft-Windows-Kernel-PnP/Device Enumeration Diagnostic
wevtutil cl Microsoft-Windows-Kernel-PnP/Driver Diagnostic
wevtutil cl Microsoft-Windows-Kernel-Power/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-Power/Thermal-Diagnostic
wevtutil cl Microsoft-Windows-Kernel-Power/Thermal-Operational
wevtutil cl Microsoft-Windows-Kernel-Prefetch/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-Process/Analytic
wevtutil cl Microsoft-Windows-Kernel-Processor-Power/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-Registry/Analytic
wevtutil cl Microsoft-Windows-Kernel-Registry/Performance
wevtutil cl Microsoft-Windows-Kernel-ShimEngine/Debug
wevtutil cl Microsoft-Windows-Kernel-ShimEngine/Diagnostic
wevtutil cl Microsoft-Windows-Kernel-ShimEngine/Operational
wevtutil cl Microsoft-Windows-Kernel-StoreMgr/Analytic
wevtutil cl Microsoft-Windows-Kernel-StoreMgr/Operational
wevtutil cl Microsoft-Windows-Kernel-WDI/Analytic
wevtutil cl Microsoft-Windows-Kernel-WDI/Debug
wevtutil cl Microsoft-Windows-Kernel-WDI/Operational
wevtutil cl Microsoft-Windows-Kernel-WHEA/Errors
wevtutil cl Microsoft-Windows-Kernel-WHEA/Operational
wevtutil cl Microsoft-Windows-Kernel-XDV/Analytic
wevtutil cl Microsoft-Windows-Known Folders API Service
wevtutil cl Microsoft-Windows-L2NA/Diagnostic
wevtutil cl Microsoft-Windows-LDAP-Client/Debug
wevtutil cl Microsoft-Windows-LSA/Diagnostic
wevtutil cl Microsoft-Windows-LSA/Operational
wevtutil cl Microsoft-Windows-LSA/Performance
wevtutil cl Microsoft-Windows-LUA-ConsentUI/Diagnostic
wevtutil cl Microsoft-Windows-LanguagePackSetup/Analytic
wevtutil cl Microsoft-Windows-LanguagePackSetup/Debug
wevtutil cl Microsoft-Windows-LanguagePackSetup/Operational
wevtutil cl Microsoft-Windows-LanguageProfile/Analytic
wevtutil cl Microsoft-Windows-LimitsManagement/Diagnostic
wevtutil cl Microsoft-Windows-LinkLayerDiscoveryProtocol/Diagnostic
wevtutil cl Microsoft-Windows-LinkLayerDiscoveryProtocol/Operational
wevtutil cl Microsoft-Windows-LiveId/Analytic
wevtutil cl Microsoft-Windows-LiveId/Operational
wevtutil cl Microsoft-Windows-MPEG2-Video-Encoder-MFT_Analytic
wevtutil cl Microsoft-Windows-MPS-CLNT/Diagnostic
wevtutil cl Microsoft-Windows-MPS-DRV/Diagnostic
wevtutil cl Microsoft-Windows-MPS-SRV/Diagnostic
wevtutil cl Microsoft-Windows-MSFTEDIT/Diagnostic
wevtutil cl Microsoft-Windows-MSPaint/Admin
wevtutil cl Microsoft-Windows-MSPaint/Debug
wevtutil cl Microsoft-Windows-MSPaint/Diagnostic
wevtutil cl Microsoft-Windows-MUI/Admin
wevtutil cl Microsoft-Windows-MUI/Analytic
wevtutil cl Microsoft-Windows-MUI/Debug
wevtutil cl Microsoft-Windows-MUI/Operational
wevtutil cl Microsoft-Windows-Media-Streaming/DMC
wevtutil cl Microsoft-Windows-Media-Streaming/DMR
wevtutil cl Microsoft-Windows-Media-Streaming/MDE
wevtutil cl Microsoft-Windows-MediaFoundation-MFCaptureEngine/MFCaptureEngine
wevtutil cl Microsoft-Windows-MediaFoundation-MFReadWrite/SinkWriter
wevtutil cl Microsoft-Windows-MediaFoundation-MFReadWrite/SourceReader
wevtutil cl Microsoft-Windows-MediaFoundation-MFReadWrite/Transform
wevtutil cl Microsoft-Windows-MediaFoundation-Performance/SARStreamResource
wevtutil cl Microsoft-Windows-MediaFoundation-PlayAPI/Analytic
wevtutil cl Microsoft-Windows-MemoryDiagnostics-Results/Debug
wevtutil cl Microsoft-Windows-Minstore/Analytic
wevtutil cl Microsoft-Windows-Minstore/Debug
wevtutil cl Microsoft-Windows-Mobile-Broadband-Experience-Api-Internal/Analytic
wevtutil cl Microsoft-Windows-Mobile-Broadband-Experience-Api/Analytic
wevtutil cl Microsoft-Windows-Mobile-Broadband-Experience-Parser-Task/Analytic
wevtutil cl Microsoft-Windows-Mobile-Broadband-Experience-Parser-Task/Operational
wevtutil cl Microsoft-Windows-Mobile-Broadband-Experience-SmsApi/Analytic
wevtutil cl Microsoft-Windows-Mobile-Broadband-Experience-SmsRouter/Admin
wevtutil cl Microsoft-Windows-Mobile-Broadband-Experience-SmsRouter/Analytic
wevtutil cl Microsoft-Windows-MobilityCenter/Performance
wevtutil cl Microsoft-Windows-Mprddm/Operational
wevtutil cl Microsoft-Windows-NCSI/Analytic
wevtutil cl Microsoft-Windows-NCSI/Operational
wevtutil cl Microsoft-Windows-NDF-HelperClassDiscovery/Debug
wevtutil cl Microsoft-Windows-NDIS-PacketCapture/Diagnostic
wevtutil cl Microsoft-Windows-NDIS/Diagnostic
wevtutil cl Microsoft-Windows-NDIS/Operational
wevtutil cl Microsoft-Windows-NFC-Class-Extension/Analytical
wevtutil cl Microsoft-Windows-NTLM/Operational
wevtutil cl Microsoft-Windows-NWiFi/Diagnostic
wevtutil cl Microsoft-Windows-Narrator/Diagnostic
wevtutil cl Microsoft-Windows-Ncasvc/Operational
wevtutil cl Microsoft-Windows-NcdAutoSetup/Diagnostic
wevtutil cl Microsoft-Windows-NcdAutoSetup/Operational
wevtutil cl Microsoft-Windows-NdisImPlatform/Operational
wevtutil cl Microsoft-Windows-Ndu/Diagnostic
wevtutil cl Microsoft-Windows-NetShell/Performance
wevtutil cl Microsoft-Windows-Network-Connection-Broker
wevtutil cl Microsoft-Windows-Network-DataUsage/Analytic
wevtutil cl Microsoft-Windows-Network-Setup/Diagnostic
wevtutil cl Microsoft-Windows-Network-and-Sharing-Center/Diagnostic
wevtutil cl Microsoft-Windows-NetworkBridge/Diagnostic
wevtutil cl Microsoft-Windows-NetworkLocationWizard/Operational
wevtutil cl Microsoft-Windows-NetworkProfile/Diagnostic
wevtutil cl Microsoft-Windows-NetworkProfile/Operational
wevtutil cl Microsoft-Windows-NetworkProvider/Operational
wevtutil cl Microsoft-Windows-NetworkProvisioning/Analytic
wevtutil cl Microsoft-Windows-NetworkProvisioning/Operational
wevtutil cl Microsoft-Windows-NetworkSecurity/Debug
wevtutil cl Microsoft-Windows-NetworkStatus/Analytic
wevtutil cl Microsoft-Windows-Networking-Correlation/Diagnostic
wevtutil cl Microsoft-Windows-Networking-RealTimeCommunication/Tracing
wevtutil cl Microsoft-Windows-NlaSvc/Diagnostic
wevtutil cl Microsoft-Windows-NlaSvc/Operational
wevtutil cl Microsoft-Windows-Ntfs/Operational
wevtutil cl Microsoft-Windows-Ntfs/Performance
wevtutil cl Microsoft-Windows-Ntfs/WHC
wevtutil cl Microsoft-Windows-NvdimmN/Analytic
wevtutil cl Microsoft-Windows-NvdimmN/Diagnostic
wevtutil cl Microsoft-Windows-NvdimmN/Operational
wevtutil cl Microsoft-Windows-OLE/Clipboard-Performance
wevtutil cl Microsoft-Windows-OLEACC/Debug
wevtutil cl Microsoft-Windows-OLEACC/Diagnostic
wevtutil cl Microsoft-Windows-OOBE-FirstLogonAnim/Diagnostic
wevtutil cl Microsoft-Windows-OOBE-Machine-Core/Diagnostic
wevtutil cl Microsoft-Windows-OOBE-Machine-DUI/Diagnostic
wevtutil cl Microsoft-Windows-OOBE-Machine-DUI/Operational
wevtutil cl Microsoft-Windows-OOBE-Machine-Plugins-Wireless/Diagnostic
wevtutil cl Microsoft-Windows-OfflineFiles/Analytic
wevtutil cl Microsoft-Windows-OfflineFiles/Debug
wevtutil cl Microsoft-Windows-OfflineFiles/Operational
wevtutil cl Microsoft-Windows-OfflineFiles/SyncLog
wevtutil cl Microsoft-Windows-OneBackup/Debug
wevtutil cl Microsoft-Windows-OneX/Diagnostic
wevtutil cl Microsoft-Windows-OneX/Operational
wevtutil cl Microsoft-Windows-OobeLdr/Analytic
wevtutil cl Microsoft-Windows-OtpCredentialProvider/Operational
wevtutil cl Microsoft-Windows-PCI/Diagnostic
wevtutil cl Microsoft-Windows-PackageStateRoaming/Analytic
wevtutil cl Microsoft-Windows-PackageStateRoaming/Debug
wevtutil cl Microsoft-Windows-PackageStateRoaming/Operational
wevtutil cl Microsoft-Windows-ParentalControls/Operational
wevtutil cl Microsoft-Windows-Partition/Analytic
wevtutil cl Microsoft-Windows-Partition/Diagnostic
wevtutil cl Microsoft-Windows-PeerToPeerDrtEventProvider/Diagnostic
wevtutil cl Microsoft-Windows-PerceptionRuntime/Operational
wevtutil cl Microsoft-Windows-PerceptionSensorDataService/Operational
wevtutil cl Microsoft-Windows-PhotoAcq/Analytic
wevtutil cl Microsoft-Windows-PlayToManager/Analytic
wevtutil cl Microsoft-Windows-PmemDisk/Analytic
wevtutil cl Microsoft-Windows-PmemDisk/Diagnostic
wevtutil cl Microsoft-Windows-PmemDisk/Operational
wevtutil cl Microsoft-Windows-Policy/Analytic
wevtutil cl Microsoft-Windows-Policy/Operational
wevtutil cl Microsoft-Windows-PortableDeviceStatusProvider/Analytic
wevtutil cl Microsoft-Windows-PortableDeviceSyncProvider/Analytic
wevtutil cl Microsoft-Windows-Power-Meter-Polling/Diagnostic
wevtutil cl Microsoft-Windows-PowerCfg/Diagnostic
wevtutil cl Microsoft-Windows-PowerCpl/Diagnostic
wevtutil cl Microsoft-Windows-PowerEfficiencyDiagnostics/Diagnostic
wevtutil cl Microsoft-Windows-PowerShell-DesiredStateConfiguration-FileDownloadManager/Analytic
wevtutil cl Microsoft-Windows-PowerShell-DesiredStateConfiguration-FileDownloadManager/Debug
wevtutil cl Microsoft-Windows-PowerShell-DesiredStateConfiguration-FileDownloadManager/Operational
wevtutil cl Microsoft-Windows-PowerShell/Admin
wevtutil cl Microsoft-Windows-PowerShell/Analytic
wevtutil cl Microsoft-Windows-PowerShell/Debug
wevtutil cl Microsoft-Windows-PowerShell/Operational
wevtutil cl Microsoft-Windows-PriResources-Deployment/Diagnostic
wevtutil cl Microsoft-Windows-PriResources-Deployment/Operational
wevtutil cl Microsoft-Windows-PrimaryNetworkIcon/Performance
wevtutil cl Microsoft-Windows-PrintBRM/Admin
wevtutil cl Microsoft-Windows-PrintDialogs/Analytic
wevtutil cl Microsoft-Windows-PrintDialogs3D/Analytic
wevtutil cl Microsoft-Windows-PrintService-USBMon/Debug
wevtutil cl Microsoft-Windows-PrintService/Admin
wevtutil cl Microsoft-Windows-PrintService/Debug
wevtutil cl Microsoft-Windows-PrintService/Operational
wevtutil cl Microsoft-Windows-ProcessStateManager/Diagnostic
wevtutil cl Microsoft-Windows-Program-Compatibility-Assistant/Analytic
wevtutil cl Microsoft-Windows-Program-Compatibility-Assistant/CompatAfterUpgrade
wevtutil cl Microsoft-Windows-Provisioning-Diagnostics-Provider/Admin
wevtutil cl Microsoft-Windows-Provisioning-Diagnostics-Provider/Debug
wevtutil cl Microsoft-Windows-Proximity-Common/Diagnostic
wevtutil cl Microsoft-Windows-Proximity-Common/Informational
wevtutil cl Microsoft-Windows-Proximity-Common/Performance
wevtutil cl Microsoft-Windows-PushNotification-Developer/Debug
wevtutil cl Microsoft-Windows-PushNotification-InProc/Debug
wevtutil cl Microsoft-Windows-PushNotification-Platform/Admin
wevtutil cl Microsoft-Windows-PushNotification-Platform/Debug
wevtutil cl Microsoft-Windows-PushNotification-Platform/Operational
wevtutil cl Microsoft-Windows-QoS-Pacer/Diagnostic
wevtutil cl Microsoft-Windows-QoS-qWAVE/Debug
wevtutil cl Microsoft-Windows-RPC-Proxy/Debug
wevtutil cl Microsoft-Windows-RPC/Debug
wevtutil cl Microsoft-Windows-RPC/EEInfo
wevtutil cl Microsoft-Windows-RRAS/Debug
wevtutil cl Microsoft-Windows-RRAS/Operational
wevtutil cl Microsoft-Windows-RadioManager/Analytic
wevtutil cl Microsoft-Windows-Ras-NdisWanPacketCapture/Diagnostic
wevtutil cl Microsoft-Windows-RasAgileVpn/Debug
wevtutil cl Microsoft-Windows-RasAgileVpn/Operational
wevtutil cl Microsoft-Windows-ReFS/Operational
wevtutil cl Microsoft-Windows-ReadyBoost/Analytic
wevtutil cl Microsoft-Windows-ReadyBoost/Operational
wevtutil cl Microsoft-Windows-ReadyBoostDriver/Analytic
wevtutil cl Microsoft-Windows-ReadyBoostDriver/Operational
wevtutil cl Microsoft-Windows-Regsvr32/Operational
wevtutil cl Microsoft-Windows-RemoteApp and Desktop Connections/Admin
wevtutil cl Microsoft-Windows-RemoteApp and Desktop Connections/Operational
wevtutil cl Microsoft-Windows-RemoteAssistance/Admin
wevtutil cl Microsoft-Windows-RemoteAssistance/Operational
wevtutil cl Microsoft-Windows-RemoteAssistance/Tracing
wevtutil cl Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Admin
wevtutil cl Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Debug
wevtutil cl Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
wevtutil cl Microsoft-Windows-RemoteDesktopServices-RemoteFX-Synth3dvsc/Admin
wevtutil cl Microsoft-Windows-RemoteDesktopServices-RemoteFX-VM-Kernel-Mode-Transport/Debug
wevtutil cl Microsoft-Windows-RemoteDesktopServices-RemoteFX-VM-User-Mode-Transport/Debug
wevtutil cl Microsoft-Windows-RemoteDesktopServices-SessionServices/Operational
wevtutil cl Microsoft-Windows-Remotefs-Rdbss/Diagnostic
wevtutil cl Microsoft-Windows-Remotefs-Rdbss/Operational
wevtutil cl Microsoft-Windows-ResetEng-Trace/Diagnostic
wevtutil cl Microsoft-Windows-Resource-Exhaustion-Detector/Operational
wevtutil cl Microsoft-Windows-Resource-Exhaustion-Resolver/Operational
wevtutil cl Microsoft-Windows-ResourcePublication/Tracing
wevtutil cl Microsoft-Windows-RestartManager/Operational
wevtutil cl Microsoft-Windows-RetailDemo/Admin
wevtutil cl Microsoft-Windows-RetailDemo/Operational
wevtutil cl Microsoft-Windows-Runtime-Graphics/Analytic
wevtutil cl Microsoft-Windows-Runtime-Networking-BackgroundTransfer/Tracing
wevtutil cl Microsoft-Windows-Runtime-Networking/Tracing
wevtutil cl Microsoft-Windows-Runtime-Web-Http/Tracing
wevtutil cl Microsoft-Windows-Runtime-WebAPI/Tracing
wevtutil cl Microsoft-Windows-Runtime-Windows-Media/WinRTCaptureEngine
wevtutil cl Microsoft-Windows-Runtime-Windows-Media/WinRTMediaStreamSource
wevtutil cl Microsoft-Windows-Runtime-Windows-Media/WinRTTranscode
wevtutil cl Microsoft-Windows-Runtime/CreateInstance
wevtutil cl Microsoft-Windows-Runtime/Error
wevtutil cl Microsoft-Windows-SENSE/Operational
wevtutil cl Microsoft-Windows-SMBClient/Analytic
wevtutil cl Microsoft-Windows-SMBClient/HelperClassDiagnostic
wevtutil cl Microsoft-Windows-SMBClient/ObjectStateDiagnostic
wevtutil cl Microsoft-Windows-SMBClient/Operational
wevtutil cl Microsoft-Windows-SMBServer/Analytic
wevtutil cl Microsoft-Windows-SMBServer/Audit
wevtutil cl Microsoft-Windows-SMBServer/Connectivity
wevtutil cl Microsoft-Windows-SMBServer/Diagnostic
wevtutil cl Microsoft-Windows-SMBServer/Operational
wevtutil cl Microsoft-Windows-SMBServer/Performance
wevtutil cl Microsoft-Windows-SMBServer/Security
wevtutil cl Microsoft-Windows-SMBWitnessClient/Admin
wevtutil cl Microsoft-Windows-SMBWitnessClient/Informational
wevtutil cl Microsoft-Windows-SPB-ClassExtension/Analytic
wevtutil cl Microsoft-Windows-SPB-HIDI2C/Analytic
wevtutil cl Microsoft-Windows-Schannel-Events/Perf
wevtutil cl Microsoft-Windows-ScmBus/Analytic
wevtutil cl Microsoft-Windows-ScmBus/Certification
wevtutil cl Microsoft-Windows-ScmBus/Diagnose
wevtutil cl Microsoft-Windows-ScmBus/Operational
wevtutil cl Microsoft-Windows-Sdbus/Analytic
wevtutil cl Microsoft-Windows-Sdbus/Debug
wevtutil cl Microsoft-Windows-Sdstor/Analytic
wevtutil cl Microsoft-Windows-Search-Core/Diagnostic
wevtutil cl Microsoft-Windows-Search-ProtocolHandlers/Diagnostic
wevtutil cl Microsoft-Windows-SearchUI/Diagnostic
wevtutil cl Microsoft-Windows-SearchUI/Operational
wevtutil cl Microsoft-Windows-SecureAssessment/Operational
wevtutil cl Microsoft-Windows-Security-Audit-Configuration-Client/Diagnostic
wevtutil cl Microsoft-Windows-Security-Audit-Configuration-Client/Operational
wevtutil cl Microsoft-Windows-Security-EnterpriseData-FileRevocationManager/Operational
wevtutil cl Microsoft-Windows-Security-ExchangeActiveSyncProvisioning/Operational
wevtutil cl Microsoft-Windows-Security-ExchangeActiveSyncProvisioning/Performance
wevtutil cl Microsoft-Windows-Security-IdentityListener/Operational
wevtutil cl Microsoft-Windows-Security-IdentityStore/Performance
wevtutil cl Microsoft-Windows-Security-LessPrivilegedAppContainer/Operational
wevtutil cl Microsoft-Windows-Security-Netlogon/Operational
wevtutil cl Microsoft-Windows-Security-SPP-UX-GC/Analytic
wevtutil cl Microsoft-Windows-Security-SPP-UX-GenuineCenter-Logging/Operational
wevtutil cl Microsoft-Windows-Security-SPP-UX-Notifications/ActionCenter
wevtutil cl Microsoft-Windows-Security-SPP-UX/Analytic
wevtutil cl Microsoft-Windows-Security-SPP/Perf
wevtutil cl Microsoft-Windows-Security-UserConsentVerifier/Audit
wevtutil cl Microsoft-Windows-Security-Vault/Performance
wevtutil cl Microsoft-Windows-SendTo/Diagnostic
wevtutil cl Microsoft-Windows-Sens/Debug
wevtutil cl Microsoft-Windows-Sensors/Debug
wevtutil cl Microsoft-Windows-Sensors/Performance
wevtutil cl Microsoft-Windows-Serial-ClassExtension-V2/Analytic
wevtutil cl Microsoft-Windows-Serial-ClassExtension/Analytic
wevtutil cl Microsoft-Windows-ServiceReportingApi/Debug
wevtutil cl Microsoft-Windows-Services-Svchost/Diagnostic
wevtutil cl Microsoft-Windows-Services/Diagnostic
wevtutil cl Microsoft-Windows-Servicing/Debug
wevtutil cl Microsoft-Windows-SettingSync-Azure/Debug
wevtutil cl Microsoft-Windows-SettingSync-Azure/Operational
wevtutil cl Microsoft-Windows-SettingSync-OneDrive/Analytic
wevtutil cl Microsoft-Windows-SettingSync-OneDrive/Debug
wevtutil cl Microsoft-Windows-SettingSync-OneDrive/Operational
wevtutil cl Microsoft-Windows-SettingSync/Analytic
wevtutil cl Microsoft-Windows-SettingSync/Debug
wevtutil cl Microsoft-Windows-SettingSync/Operational
wevtutil cl Microsoft-Windows-SettingSync/VerboseDebug
wevtutil cl Microsoft-Windows-Setup/Analytic
wevtutil cl Microsoft-Windows-SetupCl/Analytic
wevtutil cl Microsoft-Windows-SetupPlatform/Analytic
wevtutil cl Microsoft-Windows-SetupQueue/Analytic
wevtutil cl Microsoft-Windows-SetupUGC/Analytic
wevtutil cl Microsoft-Windows-ShareMedia-ControlPanel/Diagnostic
wevtutil cl Microsoft-Windows-Shell-AppWizCpl/Diagnostic
wevtutil cl Microsoft-Windows-Shell-AuthUI-BootAnim/Diagnostic
wevtutil cl Microsoft-Windows-Shell-AuthUI-Common/Diagnostic
wevtutil cl Microsoft-Windows-Shell-AuthUI-CredUI/Diagnostic
wevtutil cl Microsoft-Windows-Shell-AuthUI-CredentialProviderUser/Diagnostic
wevtutil cl Microsoft-Windows-Shell-AuthUI-Logon/Diagnostic
wevtutil cl Microsoft-Windows-Shell-AuthUI-LogonUI/Diagnostic
wevtutil cl Microsoft-Windows-Shell-AuthUI-Shutdown/Diagnostic
wevtutil cl Microsoft-Windows-Shell-ConnectedAccountState/ActionCenter
wevtutil cl Microsoft-Windows-Shell-Core/ActionCenter
wevtutil cl Microsoft-Windows-Shell-Core/AppDefaults
wevtutil cl Microsoft-Windows-Shell-Core/Diagnostic
wevtutil cl Microsoft-Windows-Shell-Core/LogonTasksChannel
wevtutil cl Microsoft-Windows-Shell-Core/Operational
wevtutil cl Microsoft-Windows-Shell-DefaultPrograms/Diagnostic
wevtutil cl Microsoft-Windows-Shell-LockScreenContent/Diagnostic
wevtutil cl Microsoft-Windows-Shell-OpenWith/Diagnostic
wevtutil cl Microsoft-Windows-Shell-Search-UriHandler
wevtutil cl Microsoft-Windows-Shell-Shwebsvc
wevtutil cl Microsoft-Windows-Shell-ZipFolder/Diagnostic
wevtutil cl Microsoft-Windows-ShellCommon-StartLayoutPopulation/Diagnostic
wevtutil cl Microsoft-Windows-ShellCommon-StartLayoutPopulation/Operational
wevtutil cl Microsoft-Windows-Shsvcs/Diagnostic
wevtutil cl Microsoft-Windows-SleepStudy/Diagnostic
wevtutil cl Microsoft-Windows-SmartCard-Audit/Authentication
wevtutil cl Microsoft-Windows-SmartCard-DeviceEnum/Operational
wevtutil cl Microsoft-Windows-SmartCard-TPM-VCard-Module/Admin
wevtutil cl Microsoft-Windows-SmartCard-TPM-VCard-Module/Operational
wevtutil cl Microsoft-Windows-SmbClient/Connectivity
wevtutil cl Microsoft-Windows-SmbClient/Diagnostic
wevtutil cl Microsoft-Windows-SmbClient/Security
wevtutil cl Microsoft-Windows-Speech-UserExperience/Diagnostic
wevtutil cl Microsoft-Windows-Spell-Checking/Analytic
wevtutil cl Microsoft-Windows-SpellChecker/Analytic
wevtutil cl Microsoft-Windows-Spellchecking-Host/Analytic
wevtutil cl Microsoft-Windows-SruMon/Diagnostic
wevtutil cl Microsoft-Windows-SrumTelemetry
wevtutil cl Microsoft-Windows-StateRepository/Debug
wevtutil cl Microsoft-Windows-StateRepository/Diagnostic
wevtutil cl Microsoft-Windows-StateRepository/Operational
wevtutil cl Microsoft-Windows-StateRepository/Restricted
wevtutil cl Microsoft-Windows-StorDiag/Operational
wevtutil cl Microsoft-Windows-StorPort/Operational
wevtutil cl Microsoft-Windows-Storage-ATAPort/Admin
wevtutil cl Microsoft-Windows-Storage-ATAPort/Analytic
wevtutil cl Microsoft-Windows-Storage-ATAPort/Debug
wevtutil cl Microsoft-Windows-Storage-ATAPort/Diagnose
wevtutil cl Microsoft-Windows-Storage-ATAPort/Operational
wevtutil cl Microsoft-Windows-Storage-ClassPnP/Admin
wevtutil cl Microsoft-Windows-Storage-ClassPnP/Analytic
wevtutil cl Microsoft-Windows-Storage-ClassPnP/Debug
wevtutil cl Microsoft-Windows-Storage-ClassPnP/Diagnose
wevtutil cl Microsoft-Windows-Storage-ClassPnP/Operational
wevtutil cl Microsoft-Windows-Storage-Disk/Admin
wevtutil cl Microsoft-Windows-Storage-Disk/Analytic
wevtutil cl Microsoft-Windows-Storage-Disk/Debug
wevtutil cl Microsoft-Windows-Storage-Disk/Diagnose
wevtutil cl Microsoft-Windows-Storage-Disk/Operational
wevtutil cl Microsoft-Windows-Storage-Storport/Admin
wevtutil cl Microsoft-Windows-Storage-Storport/Analytic
wevtutil cl Microsoft-Windows-Storage-Storport/Debug
wevtutil cl Microsoft-Windows-Storage-Storport/Diagnose
wevtutil cl Microsoft-Windows-Storage-Storport/Operational
wevtutil cl Microsoft-Windows-Storage-Tiering-IoHeat/Heat
wevtutil cl Microsoft-Windows-Storage-Tiering/Admin
wevtutil cl Microsoft-Windows-StorageManagement/Debug
wevtutil cl Microsoft-Windows-StorageManagement/Operational
wevtutil cl Microsoft-Windows-StorageSpaces-Driver/Diagnostic
wevtutil cl Microsoft-Windows-StorageSpaces-Driver/Operational
wevtutil cl Microsoft-Windows-StorageSpaces-Driver/Performance
wevtutil cl Microsoft-Windows-StorageSpaces-ManagementAgent/WHC
wevtutil cl Microsoft-Windows-StorageSpaces-SpaceManager/Diagnostic
wevtutil cl Microsoft-Windows-StorageSpaces-SpaceManager/Operational
wevtutil cl Microsoft-Windows-Store/Operational
wevtutil cl Microsoft-Windows-Subsys-Csr/Operational
wevtutil cl Microsoft-Windows-Subsys-SMSS/Operational
wevtutil cl Microsoft-Windows-Superfetch/Main
wevtutil cl Microsoft-Windows-Superfetch/PfApLog
wevtutil cl Microsoft-Windows-Superfetch/StoreLog
wevtutil cl Microsoft-Windows-Sysprep/Analytic
wevtutil cl Microsoft-Windows-System-Profile-HardwareId/Diagnostic
wevtutil cl Microsoft-Windows-SystemSettingsHandlers/Debug
wevtutil cl Microsoft-Windows-SystemSettingsThreshold/Debug
wevtutil cl Microsoft-Windows-SystemSettingsThreshold/Diagnostic
wevtutil cl Microsoft-Windows-SystemSettingsThreshold/Operational
wevtutil cl Microsoft-Windows-TCPIP/Diagnostic
wevtutil cl Microsoft-Windows-TCPIP/Operational
wevtutil cl Microsoft-Windows-TSF-msctf/Debug
wevtutil cl Microsoft-Windows-TSF-msctf/Diagnostic
wevtutil cl Microsoft-Windows-TSF-msutb/Debug
wevtutil cl Microsoft-Windows-TSF-msutb/Diagnostic
wevtutil cl Microsoft-Windows-TTS/Diagnostic
wevtutil cl Microsoft-Windows-TWinAPI/Diagnostic
wevtutil cl Microsoft-Windows-TWinUI/Diagnostic
wevtutil cl Microsoft-Windows-TWinUI/Operational
wevtutil cl Microsoft-Windows-TZSync/Analytic
wevtutil cl Microsoft-Windows-TZSync/Operational
wevtutil cl Microsoft-Windows-TZUtil/Operational
wevtutil cl Microsoft-Windows-TaskScheduler/Debug
wevtutil cl Microsoft-Windows-TaskScheduler/Diagnostic
wevtutil cl Microsoft-Windows-TaskScheduler/Maintenance
wevtutil cl Microsoft-Windows-TaskScheduler/Operational
wevtutil cl Microsoft-Windows-TaskbarCPL/Diagnostic
wevtutil cl Microsoft-Windows-TerminalServices-ClientUSBDevices/Admin
wevtutil cl Microsoft-Windows-TerminalServices-ClientUSBDevices/Analytic
wevtutil cl Microsoft-Windows-TerminalServices-ClientUSBDevices/Debug
wevtutil cl Microsoft-Windows-TerminalServices-ClientUSBDevices/Operational
wevtutil cl Microsoft-Windows-TerminalServices-LocalSessionManager/Admin
wevtutil cl Microsoft-Windows-TerminalServices-LocalSessionManager/Analytic
wevtutil cl Microsoft-Windows-TerminalServices-LocalSessionManager/Debug
wevtutil cl Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
wevtutil cl Microsoft-Windows-TerminalServices-MediaRedirection/Analytic
wevtutil cl Microsoft-Windows-TerminalServices-PnPDevices/Admin
wevtutil cl Microsoft-Windows-TerminalServices-PnPDevices/Analytic
wevtutil cl Microsoft-Windows-TerminalServices-PnPDevices/Debug
wevtutil cl Microsoft-Windows-TerminalServices-PnPDevices/Operational
wevtutil cl Microsoft-Windows-TerminalServices-Printers/Admin
wevtutil cl Microsoft-Windows-TerminalServices-Printers/Analytic
wevtutil cl Microsoft-Windows-TerminalServices-Printers/Debug
wevtutil cl Microsoft-Windows-TerminalServices-Printers/Operational
wevtutil cl Microsoft-Windows-TerminalServices-RDPClient/Analytic
wevtutil cl Microsoft-Windows-TerminalServices-RDPClient/Debug
wevtutil cl Microsoft-Windows-TerminalServices-RDPClient/Operational
wevtutil cl Microsoft-Windows-TerminalServices-RdpSoundDriver/Capture
wevtutil cl Microsoft-Windows-TerminalServices-RdpSoundDriver/Playback
wevtutil cl Microsoft-Windows-TerminalServices-RemoteConnectionManager/Admin
wevtutil cl Microsoft-Windows-TerminalServices-RemoteConnectionManager/Analytic
wevtutil cl Microsoft-Windows-TerminalServices-RemoteConnectionManager/Debug
wevtutil cl Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational
wevtutil cl Microsoft-Windows-TerminalServices-ServerUSBDevices/Admin
wevtutil cl Microsoft-Windows-TerminalServices-ServerUSBDevices/Analytic
wevtutil cl Microsoft-Windows-TerminalServices-ServerUSBDevices/Debug
wevtutil cl Microsoft-Windows-TerminalServices-ServerUSBDevices/Operational
wevtutil cl Microsoft-Windows-Tethering-Manager/Analytic
wevtutil cl Microsoft-Windows-Tethering-Station/Analytic
wevtutil cl Microsoft-Windows-ThemeCPL/Diagnostic
wevtutil cl Microsoft-Windows-ThemeUI/Diagnostic
wevtutil cl Microsoft-Windows-Threat-Intelligence/Analytic
wevtutil cl Microsoft-Windows-TunnelDriver
wevtutil cl Microsoft-Windows-UAC-FileVirtualization/Operational
wevtutil cl Microsoft-Windows-UAC/Operational
wevtutil cl Microsoft-Windows-UI-Shell/Diagnostic
wevtutil cl Microsoft-Windows-UIAnimation/Diagnostic
wevtutil cl Microsoft-Windows-UIAutomationCore/Debug
wevtutil cl Microsoft-Windows-UIAutomationCore/Diagnostic
wevtutil cl Microsoft-Windows-UIAutomationCore/Perf
wevtutil cl Microsoft-Windows-UIRibbon/Diagnostic
wevtutil cl Microsoft-Windows-USB-MAUSBHOST-Analytic
wevtutil cl Microsoft-Windows-USB-UCX-Analytic
wevtutil cl Microsoft-Windows-USB-USBHUB/Diagnostic
wevtutil cl Microsoft-Windows-USB-USBHUB3-Analytic
wevtutil cl Microsoft-Windows-USB-USBPORT/Diagnostic
wevtutil cl Microsoft-Windows-USB-USBXHCI-Analytic
wevtutil cl Microsoft-Windows-USBVideo/Analytic
wevtutil cl Microsoft-Windows-UniversalTelemetryClient/Operational
wevtutil cl Microsoft-Windows-User Control Panel Performance/Diagnostic
wevtutil cl Microsoft-Windows-User Control Panel Usage/Diagnostic
wevtutil cl Microsoft-Windows-User Control Panel/Diagnostic
wevtutil cl Microsoft-Windows-User Control Panel/Operational
wevtutil cl Microsoft-Windows-User Device Registration/Admin
wevtutil cl Microsoft-Windows-User Device Registration/Debug
wevtutil cl Microsoft-Windows-User Profile Service/Diagnostic
wevtutil cl Microsoft-Windows-User Profile Service/Operational
wevtutil cl Microsoft-Windows-User-Loader/Analytic
wevtutil cl Microsoft-Windows-User-Loader/Operational
wevtutil cl Microsoft-Windows-UserAccountControl/Diagnostic
wevtutil cl Microsoft-Windows-UserModePowerService/Diagnostic
wevtutil cl Microsoft-Windows-UserPnp/ActionCenter
wevtutil cl Microsoft-Windows-UserPnp/DeviceInstall
wevtutil cl Microsoft-Windows-UserPnp/DeviceMetadata/Debug
wevtutil cl Microsoft-Windows-UserPnp/Performance
wevtutil cl Microsoft-Windows-UserPnp/SchedulerOperations
wevtutil cl Microsoft-Windows-UxInit/Diagnostic
wevtutil cl Microsoft-Windows-UxTheme/Diagnostic
wevtutil cl Microsoft-Windows-VAN/Diagnostic
wevtutil cl Microsoft-Windows-VDRVROOT/Operational
wevtutil cl Microsoft-Windows-VHDMP-Analytic
wevtutil cl Microsoft-Windows-VHDMP-Operational
wevtutil cl Microsoft-Windows-VIRTDISK/Operational
wevtutil cl Microsoft-Windows-VPN-Client/Operational
wevtutil cl Microsoft-Windows-VPN/Operational
wevtutil cl Microsoft-Windows-VWiFi/Diagnostic
wevtutil cl Microsoft-Windows-VerifyHardwareSecurity/Admin
wevtutil cl Microsoft-Windows-VerifyHardwareSecurity/Operational
wevtutil cl Microsoft-Windows-Volume/Diagnostic
wevtutil cl Microsoft-Windows-VolumeControl/Performance
wevtutil cl Microsoft-Windows-VolumeSnapshot-Driver/Analytic
wevtutil cl Microsoft-Windows-VolumeSnapshot-Driver/Operational
wevtutil cl Microsoft-Windows-WABSyncProvider/Analytic
wevtutil cl Microsoft-Windows-WCN-Config-Registrar/Diagnostic
wevtutil cl Microsoft-Windows-WCNWiz/Analytic
wevtutil cl Microsoft-Windows-WEPHOSTSVC/Operational
wevtutil cl Microsoft-Windows-WFP/Analytic
wevtutil cl Microsoft-Windows-WFP/Operational
wevtutil cl Microsoft-Windows-WLAN-AutoConfig/Operational
wevtutil cl Microsoft-Windows-WLAN-Autoconfig/Diagnostic
wevtutil cl Microsoft-Windows-WLAN-Driver/Analytic
wevtutil cl Microsoft-Windows-WLAN-MediaManager/Diagnostic
wevtutil cl Microsoft-Windows-WLANConnectionFlow/Diagnostic
wevtutil cl Microsoft-Windows-WMI-Activity/Debug
wevtutil cl Microsoft-Windows-WMI-Activity/Operational
wevtutil cl Microsoft-Windows-WMI-Activity/Trace
wevtutil cl Microsoft-Windows-WMPDMCUI/Diagnostic
wevtutil cl Microsoft-Windows-WMPNSS-PublicAPI/Diagnostic
wevtutil cl Microsoft-Windows-WMPNSS-Service/Diagnostic
wevtutil cl Microsoft-Windows-WMPNSSUI/Diagnostic
wevtutil cl Microsoft-Windows-WPD-API/Analytic
wevtutil cl Microsoft-Windows-WPD-ClassInstaller/Analytic
wevtutil cl Microsoft-Windows-WPD-ClassInstaller/Operational
wevtutil cl Microsoft-Windows-WPD-CompositeClassDriver/Analytic
wevtutil cl Microsoft-Windows-WPD-CompositeClassDriver/Operational
wevtutil cl Microsoft-Windows-WPD-MTPBT/Analytic
wevtutil cl Microsoft-Windows-WPD-MTPClassDriver/Analytic
wevtutil cl Microsoft-Windows-WPD-MTPClassDriver/Operational
wevtutil cl Microsoft-Windows-WPD-MTPIP/Analytic
wevtutil cl Microsoft-Windows-WPD-MTPUS/Analytic
wevtutil cl Microsoft-Windows-WSC-SRV/Diagnostic
wevtutil cl Microsoft-Windows-WUSA/Debug
wevtutil cl Microsoft-Windows-WWAN-CFE/Diagnostic
wevtutil cl Microsoft-Windows-WWAN-MM-Events/Diagnostic
wevtutil cl Microsoft-Windows-WWAN-MediaManager/Diagnostic
wevtutil cl Microsoft-Windows-WWAN-NDISUIO-EVENTS/Diagnostic
wevtutil cl Microsoft-Windows-WWAN-SVC-Events/Diagnostic
wevtutil cl Microsoft-Windows-WWAN-SVC-Events/Operational
wevtutil cl Microsoft-Windows-Wcmsvc/Diagnostic
wevtutil cl Microsoft-Windows-Wcmsvc/Operational
wevtutil cl Microsoft-Windows-WebAuth/Operational
wevtutil cl Microsoft-Windows-WebIO-NDF/Diagnostic
wevtutil cl Microsoft-Windows-WebIO/Diagnostic
wevtutil cl Microsoft-Windows-WebPlatStorage-Server
wevtutil cl Microsoft-Windows-WebPlatform-SecurityBroker/Admin
wevtutil cl Microsoft-Windows-WebPlatform-SecurityBroker/Operational
wevtutil cl Microsoft-Windows-WebPlatform-SecurityBroker/Perf
wevtutil cl Microsoft-Windows-WebServices/Tracing
wevtutil cl Microsoft-Windows-WebcamProvider/Analytic
wevtutil cl Microsoft-Windows-Websocket-Protocol-Component/Tracing
wevtutil cl Microsoft-Windows-WiFiDisplay/Analytic
wevtutil cl Microsoft-Windows-Win32k/Concurrency
wevtutil cl Microsoft-Windows-Win32k/Contention
wevtutil cl Microsoft-Windows-Win32k/Messages
wevtutil cl Microsoft-Windows-Win32k/Operational
wevtutil cl Microsoft-Windows-Win32k/Power
wevtutil cl Microsoft-Windows-Win32k/Render
wevtutil cl Microsoft-Windows-Win32k/Tracing
wevtutil cl Microsoft-Windows-Win32k/UIPI
wevtutil cl Microsoft-Windows-WinHTTP-NDF/Diagnostic
wevtutil cl Microsoft-Windows-WinHttp/Diagnostic
wevtutil cl Microsoft-Windows-WinINet-Capture/Analytic
wevtutil cl Microsoft-Windows-WinINet-Config/ProxyConfigChanged
wevtutil cl Microsoft-Windows-WinINet/Analytic
wevtutil cl Microsoft-Windows-WinINet/UsageLog
wevtutil cl Microsoft-Windows-WinINet/WebSocket
wevtutil cl Microsoft-Windows-WinMDE/MDE
wevtutil cl Microsoft-Windows-WinNat/Oper
wevtutil cl Microsoft-Windows-WinNat/Trace
wevtutil cl Microsoft-Windows-WinRM/Analytic
wevtutil cl Microsoft-Windows-WinRM/Debug
wevtutil cl Microsoft-Windows-WinRM/Operational
wevtutil cl Microsoft-Windows-WinURLMon/Analytic
wevtutil cl Microsoft-Windows-Windeploy/Analytic
wevtutil cl Microsoft-Windows-Windows Defender/Operational
wevtutil cl Microsoft-Windows-Windows Defender/WHC
wevtutil cl Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurity
wevtutil cl Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurityVerbose
wevtutil cl Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
wevtutil cl Microsoft-Windows-Windows Firewall With Advanced Security/FirewallVerbose
wevtutil cl Microsoft-Windows-WindowsBackup/ActionCenter
wevtutil cl Microsoft-Windows-WindowsColorSystem/Debug
wevtutil cl Microsoft-Windows-WindowsColorSystem/Operational
wevtutil cl Microsoft-Windows-WindowsSystemAssessmentTool/Operational
wevtutil cl Microsoft-Windows-WindowsSystemAssessmentTool/Tracing
wevtutil cl Microsoft-Windows-WindowsUIImmersive/Diagnostic
wevtutil cl Microsoft-Windows-WindowsUIImmersive/Operational
wevtutil cl Microsoft-Windows-WindowsUpdateClient/Analytic
wevtutil cl Microsoft-Windows-WindowsUpdateClient/Operational
wevtutil cl Microsoft-Windows-Wininit/Diagnostic
wevtutil cl Microsoft-Windows-Winlogon/Diagnostic
wevtutil cl Microsoft-Windows-Winlogon/Operational
wevtutil cl Microsoft-Windows-Winsock-AFD/Operational
wevtutil cl Microsoft-Windows-Winsock-NameResolution/Operational
wevtutil cl Microsoft-Windows-Winsock-WS2HELP/Operational
wevtutil cl Microsoft-Windows-Winsrv/Analytic
wevtutil cl Microsoft-Windows-Wired-AutoConfig/Diagnostic
wevtutil cl Microsoft-Windows-Wired-AutoConfig/Operational
wevtutil cl Microsoft-Windows-WlanDlg/Analytic
wevtutil cl Microsoft-Windows-Wordpad/Admin
wevtutil cl Microsoft-Windows-Wordpad/Debug
wevtutil cl Microsoft-Windows-Wordpad/Diagnostic
wevtutil cl Microsoft-Windows-WorkFolders/Analytic
wevtutil cl Microsoft-Windows-WorkFolders/Debug
wevtutil cl Microsoft-Windows-WorkFolders/Operational
wevtutil cl Microsoft-Windows-WorkFolders/WHC
wevtutil cl Microsoft-Windows-Workplace Join/Admin
wevtutil cl Microsoft-Windows-XAML-Diagnostics/Default
wevtutil cl Microsoft-Windows-XAML/Default
wevtutil cl Microsoft-Windows-XAudio2/Debug
wevtutil cl Microsoft-Windows-XAudio2/Performance
wevtutil cl Microsoft-Windows-glcnd/Admin
wevtutil cl Microsoft-Windows-glcnd/Debug
wevtutil cl Microsoft-Windows-glcnd/Diagnostic
wevtutil cl Microsoft-Windows-mobsync/Diagnostic
wevtutil cl Microsoft-Windows-ntshrui
wevtutil cl Microsoft-Windows-ntshrui-perf
wevtutil cl Microsoft-Windows-osk/Diagnostic
wevtutil cl Microsoft-Windows-stobject/Diagnostic
wevtutil cl Microsoft-WindowsPhone-Connectivity-WiFiConnSvc-Channel
wevtutil cl Microsoft-WindowsPhone-LocationServiceProvider/Debug
wevtutil cl NIS-Driver-WFP/Diagnostic
wevtutil cl Navigator
wevtutil cl Network Isolation Operational
wevtutil cl OSK_SoftKeyboard_Channel
wevtutil cl Physical_Keyboard_Manager_Channel
wevtutil cl RTWorkQueueExtended
wevtutil cl RTWorkQueueTheading
wevtutil cl SMSApi
wevtutil cl Security
wevtutil cl Setup
wevtutil cl SmbWmiAnalytic
wevtutil cl System
wevtutil cl SystemEventsBroker
wevtutil cl TabletPC_InputPanel_Channel
wevtutil cl TabletPC_InputPanel_Channel/IHM
wevtutil cl TimeBroker
wevtutil cl UIManager_Channel
wevtutil cl WINDOWS_HEVCDECODER_CHANNEL
wevtutil cl WINDOWS_KS_CHANNEL
wevtutil cl WINDOWS_MFH264Enc_CHANNEL
wevtutil cl WINDOWS_MP4SDECD_CHANNEL
wevtutil cl WINDOWS_MSMPEG2ADEC_CHANNEL
wevtutil cl WINDOWS_MSMPEG2VDEC_CHANNEL
wevtutil cl WINDOWS_VC1ENC_CHANNEL
wevtutil cl WINDOWS_WMPHOTO_CHANNEL
wevtutil cl WINDOWS_wmvdecod_CHANNEL
wevtutil cl WMPSetup
wevtutil cl WMPSyncEngine
wevtutil cl Windows Networking Vpn Plugin Platform/Operational
wevtutil cl Windows Networking Vpn Plugin Platform/OperationalVerbose
wevtutil cl Windows PowerShell
wevtutil cl Windows.Globalization/Analytic
wevtutil cl muxencode
